name: Update Exchange Rates

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:         # Allows manual triggering of the workflow

jobs:
  update_rate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright

      - name: Install Playwright Browsers
        run: |
          playwright install

      - name: Open Web Client Directory
        run: |
          ls -la
          
      - name: Run Playwright Script
        run: |
          python scrape_myr.py

      - name: Commit updated JSON file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add exchange_rate.json
          git commit -m "Update exchange rate"
          git push
